import pygame as pg
from perlin_noise import PerlinNoise
FPS = 60
WIDTH, HEIGHT = 1280 + 16, 720 # ADDING 16 PIXELS TO X FIXES RENDERING OFFSET
pg.font.init()
FONT_SIZE = 12
FONT = pg.font.Font('./fonts/TerminusTTFWindows-4.49.3.ttf', FONT_SIZE)
#FONT = pg.font.Font('freesansbold.ttf', 12) #default use font
RED = 255, 0, 0
GREEN = 0, 255, 0
YELLOW = 255, 255, 0
PURPLE = 128, 0, 128

# ASSET DATA
NARRATOR_WIDTH = 150
NARRATOR_HEIGHT = 40
# All corresponding assets must be same size all items AxA and all blocks BxB, items can be dif as blocks
ITEM_SIZE = 24 # 
BLOCK_SIZE = 24 # PIXELS

# HEALTH/COMBAT GAMEPLAY
RESISTANCE_FACTOR = 0.3 # 20% damage reduction from all resistances
SKILLS_FACTOR = 0.5
WEAPON_DAMAGE_FACTOR = 0.8
RADIATION_RES_FACTOR = 0.3
RADIATION_DMG_MULTIPLIER = 0.05 #Only take 5% damage
RADIATION_EFFECT_FACTOR = 0.15
ORGAN_DRAIN_AMOUNT = 0.07
BLEEDING_CHANCE = 15
BLEEDING_DAMAGE = 0.02

#PLAYER
MAX_TRUE_HP = 100
HP_RECOVERY_AMOUNT = 0.015

# UI
ICON_SIZE = 24
ICON_SPACING = 24
ICON_X_MARGIN = 24
UI_MARGIN = 16
UI_FONT_COLOR = (0, 255, 0)
UI_SIZE_X = 320
UI_SIZE_Y = 192

# LOG
LOG_SPACING = 8
LOG_MARGIN = 64
LOG_START_X = WIDTH - UI_SIZE_X
LOG_START_Y = HEIGHT - LOG_SPACING#UI SIZE
MAX_LOGS = 12
LOG_FONT_COLOR = (255, 255, 255)

# DIRECTOR
CYCLE_DURATION = 100
SPAWN_INTERVAL_CYCLES = 5
DIFFICULTY_INCREASE_INTERVAL = 30
MIN_SPAWN_AMOUNT = 1
MAX_SPAWN_AMOUNT = 3
EDGE_SPAWN_MARGIN = 5
EDGE_SPAWN_OFFSET = BLOCK_SIZE * 3
DAYTIME_INTERVAL = 10
GAME_TIME_MINUTE_CYCLE = 2 # LOWER TIME IS FASTER CLOCK

#CLOCK
CLOCK_X = WIDTH//2
CLOCK_Y = 12